name: Publish docs via GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]
      - run: mkdocs gh-deploy --force
